config/routes.rb
Rails.application.routes.draw do

  resources :users

  resources :slides

  root 'slides#slideshow'

  get 'login' => 'sessions#login', as: :login
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy', as: :logout

  get 'slideshow' => 'slides#slideshow'

end

app/models/slide.rb
class Slide < ActiveRecord::Base
  attr_accessor :file
  before_create :save_image, :set_path
  # validates :description, presence: true

  private

  def named_path
    "public/images/" + self.file.original_filename
  end

  def set_path
    self.path = "/images/" + self.file.original_filename
  end

  def save_image
    # path = File.join(directory, name)
    # write the file
    File.open(named_path, "wb") { |f| f.write(self.file.read) }
  end

end

app/models/user.rb
require 'bcrypt'

class User < ActiveRecord::Base
  # users.password_hash in the database is a :string
  include BCrypt

  def password
    @password ||= Password.new(password_hash)
  end

  def password=(new_password)
    @password = Password.create(new_password)
    self.password_hash = @password
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def login

  end

  def create

    @user = User.find_by_email(params[:email])

    if @user.password == params[:password_hash]
      # p "login success"
      session[:id] = @user.id
      redirect_to slides_path
    else
      # p "login failed"
      redirect_to login_path
    end

  end

  def destroy
    session[:id] = nil
    redirect_to root_path
  end

end

app/controllers/slides_controller.rb
class SlidesController < ApplicationController
  before_action :set_slide, only: [:show, :edit, :update, :destroy]
  # before_action :authenticate_user!, :except => [:slideshow]
  # GET /slides
  # GET /slides.json
  def index
    @slides = Slide.all
  end

  # GET /slides/1
  # GET /slides/1.json

  def slideshow
    @transition_time = params[:transition_time] || 10
    @slides = Slide.all
  end

  def show
  end

  # GET /slides/new
  def new
    @slide = Slide.new
  end

  # GET /slides/1/edit
  def edit
  end

  # POST /slides
  # POST /slides.json
  def create
    @slide = Slide.new(slide_params)
    @slide.file = params[:slide][:file]

    respond_to do |format|
      if @slide.save
        format.html { redirect_to @slide, notice: 'Slide was successfully created.' }
        format.json { render :show, status: :created, location: @slide }
      else
        format.html { render :new }
        format.json { render json: @slide.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /slides/1
  # PATCH/PUT /slides/1.json
  def update
    @slide = Slide.find_by_id(params[:id])
    if params[:slide][:file]
      p "in if ********"
      @slide.file = params[:slide][:file]
    end
    respond_to do |format|
      if @slide.update(slide_params)
        format.html { redirect_to @slide, notice: 'Slide was successfully updated.' }
        format.json { render :show, status: :ok, location: @slide }
      else
        format.html { render :edit }
        format.json { render json: @slide.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /slides/1
  # DELETE /slides/1.json
  def destroy
    p "$"*80
    @slide.destroy
    respond_to do |format|
      format.html { redirect_to slides_url, notice: 'Slide was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_slide
      @slide = Slide.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def slide_params
      params.require(:slide).permit(:caption, :path, :end_date, :title)
    end

    def authenticate_user!
      return true if session[:id]
      redirect_to root_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :set_user, only: [:show, :edit, :update, :destroy]
  # before_action :authenticate_user!
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create

    @user = User.new(user_params)
    @user.password = params[:password]

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password_hash, :email)
    end

    def authenticate_user!
      return true if session[:id]
      redirect_to root_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_user
    p "&" * 90
    @current_user ||= User.find_by_id(session[:id]) if session[:id]
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper

end

app/helpers/slides_helper.rb
module SlidesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title DBCtv
    = stylesheet_link_tag    'application', media: 'all'
    %link{:rel => "stylesheet", :src => "//normalize-css.googlecode.com/svn/trunk/normalize.css"}/
    = csrf_meta_tags

  %body#page
    = yield

  %header
    =link_to image_tag( "gear.png", class: "img-responsive max-20p" ), slides_path

app/views/slides/_form.html.haml
.container
  .row.well
    .form-inline
      = form_for(@slide) do |f|
        - if @slide.errors.any?
          #error_explanation
            %h2
              = pluralize(@slide.errors.count, "error")
              prohibited this slide from being saved:
            %ul
              - @slide.errors.full_messages.each do |message|
                %li= message
        .input-group
          = f.label "Title:"
        .form-group
          = f.text_field :title
        .input-group
          = f.label "Caption: (optional)"
        .form-group
          = f.text_field :caption
        %br/
        %br/
        .input-group
          = f.label "File to upload:"
        .form-group
          = f.file_field :file
        %br/
        %br/
        .input-group
          = f.label "End Date:(stubbed)"
        .form-group
          = f.datetime_select :end_date
        %br/
        %br/
        .form-group
          = f.submit class: "btn btn-large btn-success"

app/views/slides/edit.html.haml
%h1 Editing slide
= render 'form'
= link_to 'Show', @slide
|
= link_to 'Back', slides_path

app/views/slides/index.html.haml
.container
  %br/
  .row.well
    =link_to "Slideshow", root_path, class: "btn btn-large btn-warning"
    =link_to 'New Slide', new_slide_path, class: "btn btn-large btn-warning"
    .pull-right
      -if current_user
        ="Logged in as: #{current_user.username}"
        =link_to "Logout", logout_path, class: "btn btn-large btn-danger"
%br/
.container
  - @slides.each do |slide|
    .row.well
      = image_tag slide.path, class: "img-responsive"
      %br/
      %p
        Title:
        = slide.title
      %p
        Captions(optional):
        = slide.caption
      %p
        File Path:
        = slide.path
      %p
        End Date:
        = slide.end_date
      %br/
      = link_to 'View', slide, class: "btn btn-large btn-success"
      = link_to 'Edit', edit_slide_path(slide), class: "btn btn-large btn-success"
      %br/
      %br/
      = button_to 'Delete', slide_path(slide), :method => :delete, class: "btn btn-large btn-danger"
      %br/
      %br/


  %br/

app/views/slides/new.html.haml
.container
  %h1 New slide
  = render 'form'
  = link_to 'Back', slides_path

app/views/slides/show.html.haml
%p#notice= notice
=image_tag @slide.path, class: "img-res"
%br/
%p
  %strong End date:
  = @slide.end_date
= link_to 'Edit', edit_slide_path(@slide)
= link_to 'Back', slides_path

app/views/slides/slideshow.html.haml
.container-fluid
  %ul.cb-slideshow
    - @slides.each do |slide|
      .row
        - slide_transition_time = (@slides.index(slide)+1) * @transition_time - @transition_time
        - total_slide_time = @transition_time * @slides.length
        %li
          %span{ :style => "-webkit-animation: imageAnimation #{total_slide_time}s linear infinite 0s; -moz-animation: imageAnimation #{total_slide_time}s linear infinite 0s; -o-animation: imageAnimation #{total_slide_time}s linear infinite 0s; -ms-animation: imageAnimation #{total_slide_time}s linear infinite 0s; animation: imageAnimation #{total_slide_time}s linear infinite 0s; -webkit-animation-delay: #{slide_transition_time}s; -moz-animation-delay: #{slide_transition_time}s; -o-animation-delay: #{slide_transition_time}s; -ms-animation-delay: #{slide_transition_time}s; animation-delay: #{slide_transition_time}s; " }
            = image_tag slide.path, class: "img-responsive fullscreen_slide"
          %div{ :style => "-webkit-animation: titleAnimation #{total_slide_time}s linear infinite 0s; -moz-animation: titleAnimation #{total_slide_time}s linear infinite 0s; -o-animation: titleAnimation #{total_slide_time}s linear infinite 0s; -ms-animation: titleAnimation #{total_slide_time}s linear infinite 0s; animation: titleAnimation #{total_slide_time}s linear infinite 0s; -webkit-animation-delay: #{slide_transition_time}s; -moz-animation-delay: #{slide_transition_time}s; -o-animation-delay: #{slide_transition_time}s; -ms-animation-delay: #{slide_transition_time}s; animation-delay: #{slide_transition_time}s;" }
            %h3
              - if slide.caption
                = slide.caption





:javascript
  setInterval(function() { window.location.reload(); }, 10*60000); //NOTE: period is passed in milliseconds

app/views/users/_form.html.haml
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :username
    = f.text_field :username
  .field
    = f.label :password
    = f.text_field :password_hash
  .field
    = f.label :email
    = f.text_field :email
  .actions
    = f.submit 'Save'

app/views/users/edit.html.haml
%h1 Editing user

= render 'form'

= link_to 'Show', @user
\|
= link_to 'Back', users_path

app/views/users/index.html.haml
%h1 Listing users

%table
  %thead
    %tr
      %th Username
      %th Password hash
      %th Email
      %th
      %th
      %th
      
  %tbody
    - @users.each do |user|
      %tr
        %td= user.username
        %td= user.password_hash
        %td= user.email
        %td= link_to 'Show', user
        %td= link_to 'Edit', edit_user_path(user)
        %td= link_to 'Destroy', user, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New User', new_user_path

app/views/users/new.html.haml
%h1 New user

= render 'form'

= link_to 'Back', users_path

app/views/users/show.html.haml
%p#notice= notice

%p
  %b Username:
  = @user.username
%p
  %b Password hash:
  = @user.password_hash
%p
  %b Email:
  = @user.email

= link_to 'Edit', edit_user_path(@user)
\|
= link_to 'Back', users_path